### ISSUE TITLE
FEATURE: Dispatch specific workflow when specific files in master are updated. Run entire stack if any other push.

### ISSUE THREAD

**Issue by chaincrucial** [chaincrucial/guild-ops-containers#1]
Track pushes to master except:

-  `containers/guild-ops-base/cncli-latest.txt`
-  `containers/guild-ops-base/cardano-hw-cli-latest.txt`

This way if the node is updated, the entire stack is rebuilt. but if either of these files are updated then a workflow_dispatch is called that relies on the existing built node and starts at the intermediate stage, reducing build time by 90% when only a tool contains an update.

**Comment by TrevorBenson** [comment]
1. Converted the on push to on path or be triggered by scheduled workflows which change calling a workflow_dispatch. Commits to guild-operators master branch will drive new guild-ops-cnode and guild-ops-cncli containers, but not rebuild the guild-ops-base, saving time rebuilding `cardano-node`. 
2. Once guild-operators alpha builds are added the `cardano-node` will be rebuilt per commit on alpha branch to ensure compiling is stable. Guild-operators master branch commits will not rebuild `cardano-node` and strictly rebuild guild-operators tools. If an instance exists where The node would require rebuilding, we can trigger stage 1 manually, or track tags for a new node-1.x.y release and trigger stage1 from master every time an old node is set aside.
3. Created a matrix build workflow. 
  - The `cardano-node-latest.txt` will kick off an entire stack workflow from guild-ops-base stage1.
  - The `guild-ops-latest.txt` will kick off from stage2 and recompile the node and all subsequent tools.
  - The `cncli-latest.txt` will kick off stage3a if a change occurs, updating stage3 with new `cncli` and rebuild stage4/latests.
  - The `cardano-hw-cli-latest.txt` will kick off stage3b if a change occurs, updating stage3 with new `cardano-hw-cli` and rebuild stage4/latests.

**Comment by chaincrucial** [comment]
LGTM! How about a treat?? :meat_on_bone:
